# Generated by Django 3.1.3 on 2020-11-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pword', models.CharField(max_length=20)),
                ('emaill', models.EmailField(max_length=30)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNew',
            fields=[
                ('regNo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30, unique=True)),
                ('lname', models.CharField(max_length=20)),
                ('pword', models.CharField(default=12345, max_length=20)),
                ('emaill', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentNew',
            fields=[
                ('regNo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30, unique=True)),
                ('lname', models.CharField(max_length=20)),
                ('pword', models.CharField(default=12345, max_length=20)),
                ('emaill', models.EmailField(max_length=30)),
                ('level', models.IntegerField()),
                ('faculty', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCoursesNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler1.studentnew')),
            ],
        ),
    ]
