# Generated by Django 3.1.3 on 2020-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Profiler1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('cName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cUnits', models.IntegerField()),
                ('cLevel', models.IntegerField()),
                ('cDescrp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reg400',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler1.studentnew')),
            ],
        ),
        migrations.CreateModel(
            name='Reg300',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler1.studentnew')),
            ],
        ),
        migrations.CreateModel(
            name='Reg200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler1.studentnew')),
            ],
        ),
        migrations.CreateModel(
            name='Reg100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler1.studentnew')),
            ],
        ),
    ]
